/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import tool.HibernateUtil;

/**
 *
 * @author amry4
 */
public class MainMenuView extends javax.swing.JFrame {

    public MainMenuView() {
        initComponents();

    }
/**
 * this function is used for showing a report internal form on a panel
 * @param Report is string datatype that referring from report file(*name*.jrxml) 
 * @throws SQLException 
 */
    public void showReport(String Report) throws SQLException {
        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        Connection c = null;
        try {
            c = sessionFactory.getSessionFactoryOptions().getServiceRegistry().
                    getService(ConnectionProvider.class).getConnection();
            JasperPrint countryPrint = JasperFillManager.fillReport(
                    getClass().getClassLoader().getResourceAsStream(Report), null, c);

            JInternalFrame report = new JInternalFrame("Report");
            report.getContentPane().add(new JRViewer(countryPrint));
            report.pack();
            report.setVisible(true);
            report.setSize(1000, 800);
            report.setFocusable(false);
            report.isClosable();
            report.setMaximizable(rootPaneCheckingEnabled);
            MainPanel.add(report);

//        JasperExportManager.exportReportToPdfFile(countryPrint,
//                "C:\\Users\\amry4\\OneDrive\\Dokumen\\NetBeansProjects\\HibernateTest\\src\\countryReport.pdf");
//        System.out.println("Pdf file has been created");
//            PReport.revalidate();
        } catch (JRException ex) {
            printStackTrace(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        MainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PRegion = new javax.swing.JMenuItem();
        PCountry = new javax.swing.JMenuItem();
        PLocation = new javax.swing.JMenuItem();
        PDepartment = new javax.swing.JMenuItem();
        PJob = new javax.swing.JMenuItem();
        PEmployee = new javax.swing.JMenuItem();
        PJobHistory = new javax.swing.JMenuItem();
        PJobGrade = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnReportCountry = new javax.swing.JMenuItem();
        btnReportRegion = new javax.swing.JMenuItem();
        btnReportLocation = new javax.swing.JMenuItem();
        btnReportDepartment = new javax.swing.JMenuItem();
        btnReportJob = new javax.swing.JMenuItem();
        btnReportEmployee = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR MANAGEMENT");
        setIconImages(null);

        MainPanel.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        PRegion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        PRegion.setText("Region");
        PRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRegionActionPerformed(evt);
            }
        });
        jMenu1.add(PRegion);

        PCountry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        PCountry.setText("Country");
        PCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCountryActionPerformed(evt);
            }
        });
        jMenu1.add(PCountry);

        PLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        PLocation.setText("Location");
        PLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLocationActionPerformed(evt);
            }
        });
        jMenu1.add(PLocation);

        PDepartment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        PDepartment.setText("Department");
        PDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDepartmentActionPerformed(evt);
            }
        });
        jMenu1.add(PDepartment);

        PJob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        PJob.setText("Job");
        PJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJobActionPerformed(evt);
            }
        });
        jMenu1.add(PJob);

        PEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_MASK));
        PEmployee.setText("Employee");
        PEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(PEmployee);

        PJobHistory.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_MASK));
        PJobHistory.setText("Job History");
        PJobHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJobHistoryActionPerformed(evt);
            }
        });
        jMenu1.add(PJobHistory);

        PJobGrade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.CTRL_MASK));
        PJobGrade.setText("Job Grade");
        PJobGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PJobGradeActionPerformed(evt);
            }
        });
        jMenu1.add(PJobGrade);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Report");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        btnReportCountry.setText("Country");
        btnReportCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportCountryActionPerformed(evt);
            }
        });
        jMenu3.add(btnReportCountry);

        btnReportRegion.setText("Region");
        btnReportRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportRegionActionPerformed(evt);
            }
        });
        jMenu3.add(btnReportRegion);

        btnReportLocation.setText("Location");
        btnReportLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportLocationActionPerformed(evt);
            }
        });
        jMenu3.add(btnReportLocation);

        btnReportDepartment.setText("Department");
        btnReportDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDepartmentActionPerformed(evt);
            }
        });
        jMenu3.add(btnReportDepartment);

        btnReportJob.setText("Job");
        btnReportJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportJobActionPerformed(evt);
            }
        });
        jMenu3.add(btnReportJob);

        btnReportEmployee.setText("Employee");
        btnReportEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportEmployeeActionPerformed(evt);
            }
        });
        jMenu3.add(btnReportEmployee);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRegionActionPerformed

        RegionView RV = new RegionView();
        RV.show();
        MainPanel.add(RV);

    }//GEN-LAST:event_PRegionActionPerformed

    private void PCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCountryActionPerformed
//        PreviewReports PR = new PreviewReports();
//        PR.show(); 
        CountryView CV = new CountryView();
        CV.show();
        MainPanel.add(CV);
    }//GEN-LAST:event_PCountryActionPerformed

    private void PLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLocationActionPerformed
        LocationView LV = new LocationView();
        LV.show();
        MainPanel.add(LV);
    }//GEN-LAST:event_PLocationActionPerformed

    private void PDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDepartmentActionPerformed
        DepartmentlView DV = new DepartmentlView();
        DV.show();
        MainPanel.add(DV);
    }//GEN-LAST:event_PDepartmentActionPerformed

    private void PJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJobActionPerformed
        JobView JV = new JobView();
        JV.show();
        MainPanel.add(JV);
    }//GEN-LAST:event_PJobActionPerformed

    private void PEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PEmployeeActionPerformed
        EmployeeView EmpV = new EmployeeView();
        EmpV.show();
        MainPanel.add(EmpV);
    }//GEN-LAST:event_PEmployeeActionPerformed

    private void PJobHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJobHistoryActionPerformed
//        JobHistoryInternalView JHV = new JobHistoryInternalView();
//        JHV.show();
//        MainPanel.add(JHV);
    }//GEN-LAST:event_PJobHistoryActionPerformed

    private void PJobGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PJobGradeActionPerformed
//        JobGradeInternalView JGV = new JobGradeInternalView();
//        JGV.show();
//        MainPanel.add(JGV);
    }//GEN-LAST:event_PJobGradeActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
//      showReport();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void btnReportCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportCountryActionPerformed
        try {
            showReport("countryReport.jasper");
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportCountryActionPerformed

    private void btnReportRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportRegionActionPerformed
        try {
            showReport("regionReport.jasper");
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportRegionActionPerformed

    private void btnReportLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportLocationActionPerformed
        try {
            showReport("locationReport.jasper");
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportLocationActionPerformed

    private void btnReportDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDepartmentActionPerformed
      try {
            showReport("departmentReport.jasper");
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportDepartmentActionPerformed

    private void btnReportJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportJobActionPerformed
        try {
            showReport("jobReport.jasper");
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportJobActionPerformed

    private void btnReportEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportEmployeeActionPerformed
       try {
            showReport("employeeReport.jasper");
        } catch (SQLException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenuView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuItem PCountry;
    private javax.swing.JMenuItem PDepartment;
    private javax.swing.JMenuItem PEmployee;
    private javax.swing.JMenuItem PJob;
    private javax.swing.JMenuItem PJobGrade;
    private javax.swing.JMenuItem PJobHistory;
    private javax.swing.JMenuItem PLocation;
    private javax.swing.JMenuItem PRegion;
    private javax.swing.JMenuItem btnReportCountry;
    private javax.swing.JMenuItem btnReportDepartment;
    private javax.swing.JMenuItem btnReportEmployee;
    private javax.swing.JMenuItem btnReportJob;
    private javax.swing.JMenuItem btnReportLocation;
    private javax.swing.JMenuItem btnReportRegion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JPanel getjPanel() {
        return MainPanel;
    }
}
