/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import tool.HibernateUtil;

/**
 *
 * @author amry4
 */
public class PreviewReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form PreviewReport
     */
    public PreviewReport() {
        initComponents();
       SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        Connection c = null;
        try {
            c = sessionFactory.getSessionFactoryOptions().getServiceRegistry().
                    getService(ConnectionProvider.class).getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(PreviewReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            JasperPrint countryPrint = JasperFillManager.fillReport(
                    getClass().getClassLoader().getResourceAsStream("CountryReport.jasper"), null, c);
            
//        JasperExportManager.exportReportToPdfFile(countryPrint,
//                "C:\\Users\\amry4\\OneDrive\\Dokumen\\NetBeansProjects\\HibernateTest\\src\\countryReport.pdf");
//        System.out.println("Pdf file has been created");
//        JasperViewer JV = new JasperViewer(countryPrint);
//        JV.setVisible(true);
//        PReport.setLayout(new java.awt.BorderLayout());
//        PReport.add(JV);
//        PReport.revalidate();
        } catch (JRException ex) {
            Logger.getLogger(PreviewReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PReport = new javax.swing.JPanel();

        javax.swing.GroupLayout PReportLayout = new javax.swing.GroupLayout(PReport);
        PReport.setLayout(PReportLayout);
        PReportLayout.setHorizontalGroup(
            PReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1065, Short.MAX_VALUE)
        );
        PReportLayout.setVerticalGroup(
            PReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PReport;
    // End of variables declaration//GEN-END:variables
}
