/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;

/**
 *
 * @author amry4
 */
public class MainMenuView extends javax.swing.JFrame {

    Color paneldefault;
    Color panelClicked;

    public MainMenuView() {
        initComponents();

        paneldefault = new Color(0,204,204);
        panelClicked = new Color(0,200,200);
        PLocation.setBackground(paneldefault);
        PRegion.setBackground(paneldefault);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        PRegion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PCountry = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PLocation = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PDepartment = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PJob = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PEmployee = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PJHistory = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPane = new javax.swing.JPanel();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PRegion.setBackground(new java.awt.Color(0, 204, 204));
        PRegion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PRegion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRegionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLocationMousePressed(evt);
            }
        });
        PRegion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel1.setText("REGION");
        PRegion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.add(PRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 120, 80));

        PCountry.setBackground(new java.awt.Color(0, 204, 204));
        PCountry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PCountryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLocationMousePressed(evt);
            }
        });
        PCountry.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel3.setText("COUNTRY");
        PCountry.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.add(PCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 120, 80));

        PLocation.setBackground(new java.awt.Color(0, 204, 204));
        PLocation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PLocationMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLocationMousePressed(evt);
            }
        });
        PLocation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel4.setText("LOCATION");
        PLocation.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 14));

        jPanel1.add(PLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, 80));

        PDepartment.setBackground(new java.awt.Color(0, 204, 204));
        PDepartment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PDepartmentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLocationMousePressed(evt);
            }
        });
        PDepartment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel5.setText("DEPARTMENT");
        PDepartment.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jPanel1.add(PDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 120, 80));

        PJob.setBackground(new java.awt.Color(0, 204, 204));
        PJob.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PJob.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PJob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PJobMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLocationMousePressed(evt);
            }
        });
        PJob.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel7.setText("JOB");
        PJob.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 16));

        jPanel1.add(PJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 120, 80));

        PEmployee.setBackground(new java.awt.Color(0, 204, 204));
        PEmployee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PEmployeeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLocationMousePressed(evt);
            }
        });
        PEmployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel6.setText("EMPLOYEE");
        PEmployee.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 16));

        jPanel1.add(PEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 120, 80));

        PJHistory.setBackground(new java.awt.Color(0, 204, 204));
        PJHistory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PJHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PJHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PJHistoryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLocationMousePressed(evt);
            }
        });
        PJHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 15)); // NOI18N
        jLabel8.setText("JOB HISTORY");
        PJHistory.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jPanel1.add(PJHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 120, 80));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HR MANAGEMENT");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 350, 50));

        javax.swing.GroupLayout jPaneLayout = new javax.swing.GroupLayout(jPane);
        jPane.setLayout(jPaneLayout);
        jPaneLayout.setHorizontalGroup(
            jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPaneLayout.setVerticalGroup(
            jPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRegionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRegionMouseClicked
        jPane.removeAll();
        RegInternalForm RV = new RegInternalForm();
        jPane.add(RV).setVisible(true);
    }//GEN-LAST:event_PRegionMouseClicked

    private void PLocationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLocationMousePressed
        PLocation.setBackground(paneldefault);
        PRegion.setBackground(panelClicked);
    }//GEN-LAST:event_PLocationMousePressed

    private void PCountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCountryMouseClicked
        new CountryView().setVisible(true);
    }//GEN-LAST:event_PCountryMouseClicked

    private void PLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLocationMouseClicked
        new LocationView().setVisible(true);
    }//GEN-LAST:event_PLocationMouseClicked

    private void PDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDepartmentMouseClicked
        new DepartmentView().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_PDepartmentMouseClicked

    private void PJobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PJobMouseClicked
        new JobsView().setVisible(true);
    }//GEN-LAST:event_PJobMouseClicked

    private void PEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PEmployeeMouseClicked
     new EmployeeView().setVisible(true);
    }//GEN-LAST:event_PEmployeeMouseClicked

    private void PJHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PJHistoryMouseClicked
         new JobHistoryView().setVisible(true);
    }//GEN-LAST:event_PJHistoryMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenuView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PCountry;
    private javax.swing.JPanel PDepartment;
    private javax.swing.JPanel PEmployee;
    private javax.swing.JPanel PJHistory;
    private javax.swing.JPanel PJob;
    private javax.swing.JPanel PLocation;
    private javax.swing.JPanel PRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
