/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author amry4
 */
public class MainMenuView extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jExit = new javax.swing.JMenuItem();
        jRegion = new javax.swing.JMenu();
        jCountries = new javax.swing.JMenu();
        jLocations = new javax.swing.JMenu();
        jEmployees = new javax.swing.JMenu();
        jJobs = new javax.swing.JMenu();
        jDepartments = new javax.swing.JMenu();
        jJobHistory = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFile.setText("File");
        jFile.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jFileMenuSelected(evt);
            }
        });

        jExit.setText("exit");
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
        });
        jFile.add(jExit);

        jMenuBar1.add(jFile);

        jRegion.setText("Regions");
        jRegion.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jRegionMenuSelected(evt);
            }
        });
        jMenuBar1.add(jRegion);

        jCountries.setText("Countries");
        jCountries.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jCountriesMenuSelected(evt);
            }
        });
        jMenuBar1.add(jCountries);

        jLocations.setText("Locations");
        jLocations.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jLocationsMenuSelected(evt);
            }
        });
        jMenuBar1.add(jLocations);

        jEmployees.setText("Employees");
        jEmployees.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jEmployeesMenuSelected(evt);
            }
        });
        jMenuBar1.add(jEmployees);

        jJobs.setText("Jobs");
        jJobs.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jJobsMenuSelected(evt);
            }
        });
        jMenuBar1.add(jJobs);

        jDepartments.setText("Departments");
        jDepartments.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jDepartmentsMenuSelected(evt);
            }
        });
        jMenuBar1.add(jDepartments);

        jJobHistory.setText("Job History");
        jJobHistory.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jJobHistoryMenuSelected(evt);
            }
        });
        jMenuBar1.add(jJobHistory);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRegionMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jRegionMenuSelected
         new RegionView().setVisible(true);
    }//GEN-LAST:event_jRegionMenuSelected

    private void jCountriesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jCountriesMenuSelected
         new CountriesView().setVisible(true);
    }//GEN-LAST:event_jCountriesMenuSelected
    private void jLocationsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jLocationsMenuSelected
          new LocationsView().setVisible(true); 
    }//GEN-LAST:event_jLocationsMenuSelected

    private void jEmployeesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jEmployeesMenuSelected
     new EmployeesView().setVisible(true); 
    }//GEN-LAST:event_jEmployeesMenuSelected

    private void jJobsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jJobsMenuSelected
       new JobsView().setVisible(true); 
    }//GEN-LAST:event_jJobsMenuSelected

    private void jDepartmentsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jDepartmentsMenuSelected
       new DepartmentsView().setVisible(true); 
    }//GEN-LAST:event_jDepartmentsMenuSelected

    private void jJobHistoryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jJobHistoryMenuSelected
       new JobHistoryView().setVisible(true); 
    }//GEN-LAST:event_jJobHistoryMenuSelected

    private void jFileMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jFileMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileMenuSelected

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jExitMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenuView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCountries;
    private javax.swing.JMenu jDepartments;
    private javax.swing.JMenu jEmployees;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenu jJobHistory;
    private javax.swing.JMenu jJobs;
    private javax.swing.JMenu jLocations;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jRegion;
    // End of variables declaration//GEN-END:variables
}
